name: Build
on: [push, pull_request, workflow_dispatch]
jobs:

  container-job:

    runs-on: ubuntu-latest

    container: node:10

    services:

      postgres:

        image: postgres

        env:
          DB_HOST: Postgres
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
          DB_NAME_DEV: postgres
          DB_NAME_TEST: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Migrations
        run: npm run migrations

      - name: Test
        run: npm run test